### ISSUE TITLE
Regarding the four parameters mentioned in section 1.7 (Set Parmeter to Visualize Harmonics) of the GRACE-Harmonic-Plots.ipynb file (include remove_files, remove_format, redistribute_removed , mask).

### ISSUE THREAD

**Issue by SingyuTang** [tsutterley/gravity-toolkit#130]
Hello, when I use the GRACE-Harmonic-Plots.ipynb file under the gravity_toolkit/notebooks folder, when I go to Section 1.7 (Set Parmeter to Visualize Harmonics), I need to set four parameters in this section for importing and formatting some files (the comment is "removed from the GRACE/ GRACE-FO data", I don't understand what was removed), these parameters include widgets.remove_file, widgets.remove_format, widgets.redistribute_removed and widgets.mask, what these files are and what they do, this seems to be related to the recovery signal leakage in section 1.8, but I can't fully understand the role of these files, especially the lines 37~70 in section 1.8, can you help me understand what these files are and how to set these parameters? If so, can you provide some supporting literature related to it, thank you!

**Comment by tsutterley** [comment]
I need to add more to the documentation. It's a continual work in progress.

So GRACE/GRACE-FO are sensitive to the total time-varying geopotential. If you are wanting to isolate a single process (like surface hydrology), then all other sources of time-varying mass should be removed. Some processes are already removed from the GRACE/GRACE-FO data (e.g. tides, non-tidal atmospheric variation, non-tidal oceanic variation). Some processes that are to be removed are their own options (e.g. Glacial Isostatic Adjustment). While other processes need to modeled/measured and then removed. That's what these options are for (removing sets of processes from the time-variable gravity data). There's a supporting repository of codes called [`model-harmonics`](https://github.com/tsutterley/model-harmonics) that has functions for creating harmonics for some different processes.

What these options do:
- `remove_file`: a data file containing harmonics to be removed from the GRACE/GRACE-FO data
- `remove_format`: the format of this file (e.g. netCDF4, HDF5)
- `redistribute_removed`: uniformly redistributes the mass of this data over the ocean so that the total integrated mass (degree 0) is 0.
- `mask`: the land-sea mask used to redistribute the data over the ocean.

More context for this can be found in [Sutterley et al. (2020)](https://doi.org/10.1029/2019EA000860).

**Comment by SingyuTang** [comment]
I get what you mean, thank you. Since I didn’t make a complete statement, I have some other questions that I would like to consult. For your convenience, I will divide them into several points and list them as follows (some of them are not problems, and they are specially listed in order to facilitate your understanding of my intention):

(1) First of all, in section 1.7 of the file, if we did not add widgets.remove_file, then we can know that in section 1.8 (Convert GRACE/GRACE-FO harmonics to output units), lines 39~69 will not be run;

(2) But the variable 'ocean_Ylms' is generated on line 30, which means that if the widgets.remove_file is not added, the variable 'ocean_Ylms' will not be used, including GIA estimates that ocean_Ylms will not be used;

(3) Does it mean that 'redistribute_removed' is only valid for 'remove_file', in other words, does the redistribution of mass only need to be for added 'remove_file'?

(4) The removal of the GIA estimate does not seem to use 'ocean_Ylms', does it mean that the mass contribution of the removed GIA estimate does not need to be redistributed?

(5) How do lines 61~67 in section 1.8 use 'ocean_Ylms' and 'Ylms', what is the role of 'ocean_Ylms' here? Why is it not necessary to use 'ocean_Ylms' to calculate the GIA estimated SH, which seems to be related to the removed mass redistribution?

(6) You say that 'redistribute_removed' acts to redistribute the mass of this data evenly across the ocean, does point (5) have anything to do with that? Why uniform redistribution over the ocean? This seems to only apply to indirect geophysical leaks like GIA. Is it to better remove the related processing of land-to-ocean leaks?

(7) Extending from question (6), have you considered the direct geophysical leakage error part after filtering? I don't seem to see that in the code.

I am very troubled by this. My question may not be very professional or even look stupid, I hope you can enlighten me, thank you.

**Comment by tsutterley** [comment]
Hi @SingyuTang,

1. Yes, the remove file portion will only be run if there are specified files to be removed.
2. if the `redistribute_removed` flag is set but there are no files to be removed, then yes `ocean_Ylms` will be generated but unused. Shouldn't be a huge waste of computational time in any case.
3. Yes, that option is only for if files are being removed. I could have it so the widgets only toggle into view if there are files added to the remove file text widget.
4. GIA does not use `ocean_Ylms` as GIA is a solid Earth process. The ocean redistribution can be thought of as a uniform redistribution of _water_ mass onto the ocean as a sea level contribution. The ocean redistribution also does nothing if degree 0 of the removed file is equal to 0 (i.e. total integrated mass is equal to 0). Degree 0 of GIA is equal to 0 as it is a mass redistribution and not a change in total mass.
5. `Ylms` is the summation of all files to be removed. `ocean_Ylms` is used to redistribute the total mass for each time step. Example: terrestrial water storage (TWS) anomalies on land vary with time. Using the ocean redistribution functionality will take the total integrated TWS mass at a time step, and uniformly distribute that mass over the ocean. In that scenario, the ocean mass is equal to the negative of the land mass, and the total mass is then equal to 0. GIA is different as it is a solid Earth process, and the redistribution over the ocean wouldn't make physical sense.
6. Right. A better solution than a uniform redistribution is to solve the sea level equation for hydrological anomalies to compensate for the spatial pattern of the induced oceanic change. This is actually what I do in my mass balance analyses. The remove file option is for trying to isolate a single process of interest.
7. Yes. This notebook is just a demo. Calculating the leakage terms (and the uncertainty in each leakage term) is a major part of calculating a total mass estimate. Happy to talk more about that.

These are good questions and I think a good discussion topic.

**Comment by SingyuTang** [comment]
(1) Hello, you mentioned that GIA is a solid earth process in both the 4th and 5th answers. I also checked the "ICE-6G" model, and it is indeed as you said that degree 0 of GIA is equal to 0, so that the mass change after the integral of the GIA part is zero. Therefore, redistribution on the ocean will not be of practical use. Is this what you mean?

(2) In addition, I still want to ask whether the mass change related to GIA is 0 from [degree 0 of GIA is equal to 0] and [degree 0 has a linear relationship with the mass of the earth]? degree 0 of GIA is equal to 0 will cause mass change?

(3) Why do you need to redistribute first and then remove this part of the contribution from GRACE SH? Is it possible to directly remove this part of the quality contribution? What is its function?

(4) I don't seem to understand what you mean, I seem to confuse (1) and (2) I just mentioned. Is there relevant literature detailing the redistribution of mass in the ocean that you mentioned in your 4th and 5th answers that can be used for study? I'm very new to this and would like to know why this is done.

(5) In the 4th question and answer you said, GIA does not apply "ocean_Ylms", because it is a solid earth process and will not have any effect in ocean redistribution, so it does not belong to "remove_file", so what is said here What procedures might "remove_file" contain? Whether they both apply to redistributing the quality of that data evenly across the ocean, I don't seem to quite get it.

**Comment by SingyuTang** [comment]
I think if you mean that the water mass on land and the water mass on the ocean sum to zero, first calculate the TWS total mass in a single time step, the TWS total mass is numerically inverse to the ocean mass change, so this part can be utilized The mass is evenly distributed over the ocean, "ocean_Ylms" is not used since GIA is not part of oceanography. The even distribution of this part of the mass on the ocean may be disturbed by some factors, so it is necessary to introduce "remove_file" to remove this part of the interference, but I may not know much about this part of the interference.
The above is roughly my understanding. I don’t know if my idea is correct. If there is any inappropriateness, please point it out in time. If it is correct, what may be the possible influencing factors involved in "remove_file". I don't know how to create or find these files, and I don't know how to use this part of your code (remove_file). I hope you can give me some help. Thank you.

**Comment by tsutterley** [comment]
"TWS total mass is numerically inverse to the ocean mass change" -> Yes, that is exactly what this does. Calculate the total land mass, calculate what the equivalent sea level height would be for that mass, and then add it to the harmonic fields.

I create files to be removed from the GRACE/GRACE-FO data using the extension routines found in [`model-harmonics`](https://github.com/tsutterley/model-harmonics). 

1. Yes, GIA is a solid Earth process (the long-term relaxation of the solid Earth due to the ice age deglaciation), so the sea level redistribution makes no physical sense. Degree 0 of GIA is also equal to 0 as it is a mass redistribution and not a mass change (there is no addition or loss of crust or mantle material due to GIA).

2. Degree 0 is related to the total mass with the following relation $\Delta M = \frac{4}{3}\pi a^3\rho_e\Delta C_{00}$.
i.e. as a scaling factor on the total mass of the planet. For a single process degree 0 might not be 0 (such as with terrestial hydrology as there may be more of less water stored on land at a given time, or with glaciology as there may be a loss of ice to the ocean or proglacial lakes). For the integration of all processes, degree 0 is effectively and treated as 0 (technically comets and meteors can add mass to the Earth and there is a loss of atmosphere to space, but these are negligible changes for practicality). For GIA, as it is simply a redistribution of mass, degree 0 is also 0.
3. Getting more realistic estimates of the leakage signal for the processes removed.
4. Not off the top of my head for this particular part of the processing chain. But [Wahr et al. (1998)](http://dx.doi.org/10.1029/98JB02844) and [Swenson et al. (2002)](http://dx.doi.org/10.1029/2001JB00057) are always good reads.
5. It depends on the geophysical process that one is wanting to isolate from the GRACE/GRACE-FO data. If someone is interested in groundwater for instance, then they might want to remove model estimates of surface water. Keep in mind that everything removed from the GRACE/GRACE-FO data should have an associated uncertainty that is added to the total error budget.

<img src="https://www.mdpi.com/remotesensing/remotesensing-11-02108/article_deploy/html/images/remotesensing-11-02108-g001.png" />

**Comment by SingyuTang** [comment]
The work and answers you've done have been great and I've learned a lot. For example, if I want to calculate groundwater, then I need to remove the surface water, soil water, runoff, snow water and other components on land, so I can model this part to remove it, because this part of the quality belongs to the quality Change, I can also redistribute its quality on the ocean, which means I can enable both "remove_file" and "redistribute_removed" functions in your notebook. I think it should be the same as what you said. But at the same time, I think there is another problem. Due to evapotranspiration, the mass changes on land and ocean may not be completely opposite in value, but some of them exist in the atmosphere. Have you considered this part of the error?

**Comment by tsutterley** [comment]
Great! Glad we're getting you towards your research goals.
I typically remove total surface water ($P-ET+S_{soil}+S_{canopy}+S_{snow}$), and I suppose I make the assumption that averaged over a month the mass of total atmospheric water vapor is largely constant. Interesting thought.

**Comment by SingyuTang** [comment]
Thank you very much for your help and look forward to more and better results from you.

**Comment by tsutterley** [comment]
Anytime. I'll close this issue for now but feel free to reopen at any time.

**Comment by SingyuTang** [comment]
If I want to perform spherical harmonic expansion on other ground fluxes, how can I calculate it? I want to perform similar processing to GRACE after unfolding these data to ensure the comparability of the two sets of data.
